#!/usr/bin/env python3
"""Generate Mathera curriculum.json — Eras I–VII with correct IV–VII counts (743)."""
import json
from pathlib import Path

STEPS = {
    "a": "See it",
    "b": "Name it",
    "c": "Hold it",
    "d": "Use it",
}

def steps():
    return [
        {"id": "a", "label": STEPS["a"]},
        {"id": "b", "label": STEPS["b"]},
        {"id": "c", "label": STEPS["c"]},
        {"id": "d", "label": STEPS["d"]},
    ]

def make_skills(era_roman, domain_idx, titles, starter_n=2):
    out = []
    for i, title in enumerate(titles, 1):
        sid = f"{era_roman}.{domain_idx}.{i:02d}"
        if i <= starter_n:
            state = "seed" if i > 1 else "growing"
            was = "seed" if i == 1 else None
        else:
            state = "inferred"
            was = None
        sk = {
            "id": sid,
            "title": title,
            "star": False,
            "was": was,
            "steps": ["a", "b", "c", "d"],
            "state": state,
        }
        if state == "growing":
            sk["step"] = "b"
        out.append(sk)
    return out

def pad(titles, n, prefix):
    titles = list(titles)
    i = len(titles) + 1
    while len(titles) < n:
        titles.append(f"{prefix} · skill {i}")
        i += 1
    return titles[:n]

# ─── Era IV Solve (199) ───────────────────────────────────────────
IV = [
    ("Equations & inequalities", [
        "Solve one-step equations",
        "Solve two-step equations",
        "Solve multi-step equations",
        "Solve and graph inequalities",
        "Compound inequalities",
    ]),
    ("Functions", [
        "Function or not",
        "Function notation f(x)",
        "Evaluate functions",
        "Domain from a graph",
        "Range from a graph",
        "Domain from an equation",
        "Vertical line test",
        "Independent & dependent",
        "Discrete vs continuous",
        "Increasing & decreasing",
        "Maxima & minima (visual)",
        "Average rate of change",
        "Piecewise graphs",
        "Even & odd (visual)",
        "Inverse from a table",
    ]),
    ("Linear functions", [
        "Slope from two points",
        "Slope from a graph",
        "Slope-intercept form",
        "Point-slope form",
        "Standard form",
        "Graph from intercepts",
        "Parallel & perpendicular slopes",
        "Write equation from graph",
        "Model with linear functions",
    ]),
    ("Systems", [
        "Solve by graphing",
        "Solve by substitution",
        "Solve by elimination",
        "Systems of inequalities",
        "Three-variable intro",
        "Consistent & inconsistent",
        "Dependent systems",
        "Word: mixture",
        "Word: motion",
        "Word: value",
        "Break-even models",
        "Linear programming region",
        "Matrix row ops intro",
        "Augmented matrices",
        "Gaussian elimination (2×2)",
    ]),
    ("Exponents & radicals", [
        "Product & quotient rules",
        "Power rules",
        "Negative exponents",
        "Rational exponents",
        "Simplify radicals",
        "Operations with radicals",
        "Rationalize denominators",
    ]),
    ("Polynomials", [
        "Classify by degree & terms",
        "Add & subtract polynomials",
        "Multiply monomials",
        "FOIL & distribute",
        "Special products",
        "GCF factoring",
        "Factor trinomials a=1",
        "Factor trinomials a≠1",
        "Difference of squares",
        "Sum/diff of cubes",
        "Factor by grouping",
        "Factor completely",
        "Divide by monomial",
        "Long division of polynomials",
        "Synthetic division",
        "Remainder theorem",
    ]),
    ("Quadratics", [
        "Graph parabolas from vertex",
        "Axis of symmetry",
        "Intercept form",
        "Vertex form conversions",
        "Complete the square",
        "Quadratic formula",
        "Discriminant",
        "Complex roots intro",
        "Projectile models",
        "Max/min word problems",
        "Factor to solve",
        "Square-root method",
        "Systems: linear-quadratic",
        "Quadratic inequalities",
        "Transformations of y=x²",
        "Focus–directrix intro",
        "Fit a quadratic",
    ]),
    ("Complex numbers", [
        "Imaginery unit i",
        "Powers of i",
        "Add & subtract complex",
        "Multiply complex",
        "Complex conjugates",
        "Divide complex",
        "Modulus",
        "Argand plane",
        "Polar form",
        "De Moivre (powers)",
        "nth roots of complex",
        "Complex from quadratics",
        "Operations in polar form",
        "Euler's formula glimpse",
        "Complex conjugates & graphs",
        "Applications of complex",
    ]),
    ("Function toolkit", [
        "Parent functions gallery",
        "Vertical shifts",
        "Horizontal shifts",
        "Reflections",
        "Stretches & compressions",
        "Compose transformations",
        "f(g(x)) composition",
        "Decompose functions",
        "One-to-one & inverses",
        "Find inverse algebraically",
        "Graph inverse",
        "Restrict domain for inverse",
        "Absolute value graphs",
        "Step & piecewise build",
        "Combine functions (+ − × ÷)",
        "Difference quotient",
        "Symmetry tests",
        "End behavior (visual)",
    ]),
    ("Polynomial functions", [
        "End behavior & degree",
        "Zeros & multiplicity",
        "Sketch from factors",
        "Intermediate Value Theorem",
        "Rational Root Theorem",
        "Factor theorem applications",
        "Complex zeros conjugate pairs",
        "Descartes' rule of signs",
        "Upper/lower bounds",
        "Graph with calculus-free tools",
        "Polynomial inequalities",
        "Model with polynomials",
        "Compare polynomial models",
        "Turning points bound",
    ]),
    ("Rational & radical functions", [
        "Simplify rational expressions",
        "Multiply/divide rationals",
        "Add/subtract rationals",
        "Complex fractions",
        "Vertical asymptotes",
        "Horizontal & slant asymptotes",
        "Holes in graphs",
        "Graph rational functions",
        "Solve rational equations",
        "Rational inequalities",
        "Square-root functions",
        "Cube-root functions",
        "Solve radical equations",
        "Extraneous roots",
    ]),
    ("Exponential & logarithmic", [
        "Exponential growth graphs",
        "Exponential decay",
        "e and continuous growth",
        "Log as inverse of exp",
        "Common & natural logs",
        "Log properties: product",
        "Log properties: quotient/power",
        "Change of base",
        "Solve exponential equations",
        "Solve log equations",
        "Exponential models (finance)",
        "Half-life & doubling",
        "Newton's law of cooling",
        "Logarithmic scales",
        "Graph log functions",
        "Transform exp & log",
        "Compare growth rates",
    ]),
    ("Sequences & series", [
        "Sequence notation a_n",
        "Arithmetic sequences",
        "Arithmetic series",
        "Geometric sequences",
        "Geometric series (finite)",
        "Infinite geometric |r|<1",
        "Recursive definitions",
        "Explicit from recursive",
        "Sigma notation",
        "Partial sums",
        "Fibonacci & variants",
        "Applications of series",
        "Binomial coefficients",
        "Binomial theorem",
    ]),
    ("Counting & probability", [
        "Fundamental counting",
        "Permutations",
        "Combinations",
        "Distinguishable permutations",
        "Pascal & combinations",
        "Sample spaces",
        "Theoretical probability",
        "Independent events",
        "Dependent events",
        "Mutually exclusive",
        "Conditional probability",
        "Expected value intro",
    ]),
    ("Data & distributions", [
        "Dot plots & histograms",
        "Mean, median, mode",
        "Range & IQR",
        "Box plots",
        "Variance & SD",
        "Z-scores",
        "Normal curve intro",
        "Empirical rule",
        "Scatter & correlation",
        "Least-squares line",
    ]),
]

# ─── Era V Prove (173) ────────────────────────────────────────────
V = [
    ("Logic & proof", [
        "Statements & negations",
        "Conditional statements",
        "Converse, inverse, contrapositive",
        "Biconditionals",
        "Inductive reasoning",
        "Deductive reasoning",
        "Laws of detachment & syllogism",
        "Algebraic proof",
        "Two-column proof intro",
        "Paragraph proofs",
        "Indirect proof (contradiction)",
        "Counterexamples",
        "Quantifiers ∀ ∃",
        "Set language in proofs",
        "Proof planning",
        "Common proof patterns",
    ]),
    ("Lines & angles", [
        "Angle pairs & complements",
        "Vertical angles",
        "Parallel lines & transversals",
        "Prove lines parallel",
        "Angle sum on a line",
        "Perpendicular theorems",
    ]),
    ("Triangles", [
        "Triangle classification",
        "Triangle angle sum",
        "Exterior angle theorem",
        "SSS congruence",
        "SAS congruence",
        "ASA & AAS",
        "HL for right triangles",
        "CPCTC",
        "Isosceles triangle theorems",
        "Triangle inequality",
        "Hinge theorem",
        "Medians & centroid",
        "Altitude & orthocenter",
        "Perp. bisectors & circumcenter",
    ]),
    ("Polygons", [
        "Interior angle sum",
        "Exterior angles of polygons",
        "Regular polygons",
        "Parallelogram properties",
        "Rectangle, rhombus, square",
        "Trapezoids & kites",
        "Prove parallelogram",
        "Coordinate proof of quads",
        "Area formulas review",
    ]),
    ("Similarity", [
        "Similar figures definition",
        "AA similarity",
        "SSS & SAS similarity",
        "Corresponding lengths",
        "Triangle proportionality",
        "Angle bisector theorem",
        "Similar right triangles",
        "Geometric mean in right Δ",
        "Scale drawings",
        "Indirect measurement",
        "Areas of similar figures",
        "Volumes of similar solids",
    ]),
    ("Right-triangle trig", [
        "Pythagorean theorem",
        "Converse of Pythagoras",
        "Special 45-45-90",
        "Special 30-60-90",
        "Sine & cosine ratios",
        "Tangent ratio",
        "Solve right triangles",
        "Angle of elevation/depression",
        "Inverse trig for angles",
        "Cofunction identities",
        "Pythagorean identity intro",
        "Applications: navigation",
        "Applications: surveying",
        "Trig in coordinate plane",
    ]),
    ("General triangles", [
        "Law of sines",
        "Ambiguous case SSA",
        "Law of cosines",
        "Area: (1/2)ab sin C",
        "Heron's formula",
        "Solve SAS / ASA / SSA",
        "Solve SSS / SAS",
        "Bearing problems",
        "Vectors in the plane intro",
    ]),
    ("Circles", [
        "Circle vocabulary",
        "Central angles & arcs",
        "Inscribed angles",
        "Angles from chords",
        "Tangents from a point",
        "Tangent–chord angles",
        "Intersecting chords",
        "Secant & tangent lengths",
        "Arc length",
        "Sector area",
        "Segment area",
        "Equation of a circle",
        "Complete square for circle",
        "Inscribed & circumscribed",
        "Cyclic quadrilaterals",
        "Power of a point",
        "Common tangent constructions",
    ]),
    ("Trig functions", [
        "Unit circle definition",
        "Radians & degrees",
        "Coterminal angles",
        "Reference angles",
        "Sine & cosine graphs",
        "Amplitude & period",
        "Phase shift",
        "Tangent graph",
        "Sec, csc, cot graphs",
        "Domain & range of trig",
        "Inverse sine/cosine/tan",
        "Solve for angles on circle",
        "Sinusoidal models",
        "Harmonic motion intro",
        "Polar angle sense",
    ]),
    ("Identities & equations", [
        "Reciprocal identities",
        "Quotient identities",
        "Pythagorean identities",
        "Even/odd trig",
        "Cofunction identities",
        "Sum & difference formulas",
        "Double-angle formulas",
        "Half-angle formulas",
        "Verify identities",
        "Solve trig equations (basic)",
        "Solve trig equations (multi)",
        "Product-to-sum glimpse",
    ]),
    ("Coordinate geometry", [
        "Distance & midpoint",
        "Partition a segment",
        "Slope criteria proofs",
        "Equation of a line review",
        "Parallel/perp in coordinates",
        "Coordinate triangle proofs",
        "Locus problems",
        "Area via coordinates",
        "Transformations on plane",
    ]),
    ("Conic sections", [
        "Parabola focus–directrix",
        "Parabola equations",
        "Ellipse definition",
        "Ellipse standard form",
        "Hyperbola definition",
        "Hyperbola standard form",
        "Classify conics",
        "Complete the square (conics)",
        "Translate conics",
        "Eccentricity",
        "Applications of conics",
    ]),
    ("Transformations", [
        "Translations",
        "Reflections",
        "Rotations 90/180/270",
        "Dilations",
        "Composition of isometries",
        "Glide reflections",
        "Symmetry groups intro",
        "Mapping figures",
        "Coordinate rules",
        "Invariant properties",
        "Tessellations",
        "Frieze patterns glimpse",
    ]),
    ("Solids", [
        "Prisms & cylinders",
        "Pyramids & cones",
        "Spheres",
        "Surface area",
        "Volume formulas",
        "Cavalieri's principle",
        "Cross sections",
        "Nets & 3D reasoning",
    ]),
    ("Constructions", [
        "Copy a segment",
        "Copy an angle",
        "Perpendicular bisector",
        "Angle bisector",
        "Parallel through a point",
        "Equilateral triangle",
        "Incircle & circumcircle",
        "Tangent from external point",
        "Classical impossible glimpse",
    ]),
]

# ─── Era VI Motion (174) ──────────────────────────────────────────
VI = [
    ("Limits & continuity", [
        "Intuitive limit idea",
        "Limit from a table",
        "Limit from a graph",
        "One-sided limits",
        "Limit laws",
        "Direct substitution",
        "Factoring to find limits",
        "Rationalize for limits",
        "Limits at infinity",
        "Infinite limits & asymptotes",
        "Squeeze theorem",
        "Trig limits (sin x)/x",
        "Continuity at a point",
        "Types of discontinuity",
        "IVT applications",
        "Limits of piecewise",
        "ε–δ definition intro",
        "Limit of a sequence",
        "Unbounded behavior",
        "Comparing growth (limits)",
    ]),
    ("Derivatives", [
        "Tangent slope idea",
        "Definition of derivative",
        "Derivative as function",
        "Differentiability vs continuity",
        "Power rule",
        "Constant & sum rules",
        "Product rule",
        "Quotient rule",
        "Chain rule",
        "Derivatives of trig",
        "Derivatives of exp & log",
        "Implicit differentiation",
        "Higher-order derivatives",
        "Derivative from graph",
        "Numerical derivatives",
        "Logarithmic differentiation",
        "Inverse function derivatives",
        "Related rates setup",
    ]),
    ("Applications of derivatives", [
        "Position, velocity, accel",
        "Related rates problems",
        "Linearization",
        "Differentials",
        "Extreme Value Theorem",
        "Critical points",
        "Closed interval method",
        "Mean Value Theorem",
        "Rolle's theorem",
        "First derivative test",
        "Second derivative test",
        "Concavity & inflection",
        "Curve sketching",
        "Optimization (geometry)",
        "Optimization (business)",
        "Newton's method",
        "l'Hôpital's rule",
        "Indeterminate forms",
        "Motion along a line",
        "Marginal analysis",
        "Summary: f, f′, f″",
    ]),
    ("Integrals", [
        "Area under a curve idea",
        "Riemann sums",
        "Definite integral definition",
        "Midpoint & trapezoid rules",
        "Antiderivatives",
        "Indefinite integrals",
        "Fundamental Theorem I",
        "Fundamental Theorem II",
        "Net change theorem",
        "Substitution (u-sub)",
        "Integrals of trig",
        "Integrals of exp & log",
        "Even & odd integrands",
        "Average value of a function",
        "Accumulation functions",
    ]),
    ("Integration techniques", [
        "Integration by parts",
        "Trig integrals (powers)",
        "Trig substitution",
        "Partial fractions (linear)",
        "Partial fractions (quadratic)",
        "Improper integrals (∞)",
        "Improper integrals (discont.)",
        "Completing square in integrals",
        "Rationalizing substitutions",
        "Tables of integrals",
        "Numerical integration error",
        "Strategy: which method?",
        "Reduction formulas glimpse",
        "Integrals yielding inverse trig",
        "Hyperbolic intro (optional)",
        "CAS vs by-hand judgment",
    ]),
    ("Applications of integrals", [
        "Area between curves",
        "Disk method",
        "Washer method",
        "Shell method",
        "Arc length",
        "Surface of revolution",
        "Work (springs, pumps)",
        "Hydrostatic force",
        "Moments & center of mass",
        "Probability density intro",
        "Present & future value",
        "Biology: cardiac output",
        "Consumer/producer surplus",
        "Volume by known cross-section",
        "Compare volume methods",
    ]),
    ("Differential equations I", [
        "What is a DE?",
        "Solution verification",
        "Direction fields",
        "Euler's method",
        "Separable equations",
        "Exponential growth/decay DE",
        "Newton's law of cooling DE",
        "Logistic equation",
        "Mixing problems",
        "First-order linear (μ)",
        "Existence & uniqueness idea",
        "Autonomous equations",
    ]),
    ("Parametric & polar", [
        "Parametric equations",
        "Eliminate the parameter",
        "Derivatives dy/dx parametric",
        "Arc length parametric",
        "Polar coordinates",
        "Convert polar ↔ cartesian",
        "Graph polar roses & limaçons",
        "Tangents in polar",
        "Area in polar",
        "Arc length in polar",
        "Conics in polar",
        "Parametric motion apps",
    ]),
    ("Sequences & series", [
        "Sequence convergence",
        "Monotone & bounded",
        "Series & partial sums",
        "Geometric series review",
        "Telescoping series",
        "Divergence test",
        "Integral test",
        "Comparison tests",
        "Alternating series",
        "Ratio & root tests",
        "Absolute vs conditional",
    ]),
    ("Power & Taylor series", [
        "Power series idea",
        "Radius of convergence",
        "Interval of convergence",
        "Differentiate power series",
        "Integrate power series",
        "Taylor polynomials",
        "Taylor & Maclaurin series",
        "Common Maclaurin series",
        "Binomial series",
        "Remainder estimates",
        "Approximate integrals",
        "Solving DE with series",
        "Analytic functions glimpse",
        "Fourier vs Taylor contrast",
        "Applications: constants",
        "Power series manipulations",
    ]),
    ("Statistical inference", [
        "Sampling distributions",
        "CLT idea",
        "Confidence intervals (mean)",
        "Confidence intervals (prop.)",
        "Hypothesis test logic",
        "p-values",
        "t-procedures",
        "Chi-square intro",
        "Type I / Type II errors",
    ]),
    ("Mechanics", [
        "Displacement from velocity",
        "Work–energy glimpse",
        "Hooke's law & springs",
        "Center of mass (calc)",
        "Projectile via calc",
        "Simple harmonic from DE",
        "Escape velocity idea",
        "Kepler glimpse",
        "Force & acceleration models",
    ]),
]

# ─── Era VII Space (197) ──────────────────────────────────────────
VII = [
    ("Vectors in Rⁿ", [
        "Vector geometry in R²/R³",
        "Vector addition & scaling",
        "Dot product",
        "Orthogonality",
        "Projections",
        "Cross product",
        "Lines in R³",
        "Planes in R³",
        "Distances: point–line–plane",
        "Linear combinations",
        "Span of vectors",
        "Norm & unit vectors",
    ]),
    ("Linear systems", [
        "Row echelon form",
        "Reduced row echelon",
        "Gaussian elimination",
        "Free variables & params",
        "Homogeneous systems",
        "Consistency criteria",
        "Rank idea",
        "Applications: networks",
        "Applications: balance",
    ]),
    ("Matrix algebra", [
        "Matrix operations",
        "Matrix multiplication",
        "Identity & inverse",
        "Elementary matrices",
        "Solve via inverse",
        "Transpose",
        "Block matrices",
        "Matrix powers",
        "LU factorization intro",
        "Sparse vs dense",
        "Computer arithmetic caution",
        "Affine maps as matrices",
    ]),
    ("Vector spaces", [
        "Axioms of a vector space",
        "Subspaces",
        "Null space",
        "Column & row space",
        "Basis",
        "Dimension",
        "Coordinates in a basis",
        "Change of basis",
        "Rank–nullity theorem",
        "Examples: P_n, C[a,b]",
        "Affine subspaces",
        "Direct sums",
        "Isomorphism of spaces",
        "Standard bases",
        "Extending independent sets",
        "Extracting bases from spans",
    ]),
    ("Linear transformations", [
        "Definition & examples",
        "Matrix of a linear map",
        "Kernel & image",
        "Composition of maps",
        "Invertible transformations",
        "Similarity of matrices",
        "Projections as maps",
        "Rotations & reflections",
        "Rank of a transformation",
    ]),
    ("Determinants", [
        "2×2 and 3×3 determinants",
        "Cofactor expansion",
        "Properties of det",
        "Det & invertibility",
        "Det as volume",
        "Cramer's rule",
        "Adjugate & inverse",
        "Det under row ops",
        "Orientation & sign",
    ]),
    ("Eigenvalues & eigenvectors", [
        "Eigenvalue equation",
        "Characteristic polynomial",
        "Eigenspaces",
        "Diagonalization",
        "When diagonalizable?",
        "Powers via diagonalization",
        "Markov chains intro",
        "Differential systems preview",
        "Complex eigenvalues",
    ]),
    ("Orthogonality", [
        "Orthogonal sets",
        "Orthonormal bases",
        "Gram–Schmidt",
        "QR factorization",
        "Orthogonal projections",
        "Least squares",
        "Normal equations",
        "Orthogonal matrices",
        "Fourier via ortho glimpse",
        "Cauchy–Schwarz",
        "Triangle inequality (norms)",
        "Best approximation",
    ]),
    ("Symmetric matrices & SVD", [
        "Spectral theorem (sym)",
        "Orthogonal diagonalization",
        "Quadratic forms",
        "Positive definite",
        "SVD idea",
        "Singular values",
        "Low-rank approximation",
        "PCA glimpse",
    ]),
    ("Functions of several variables", [
        "Graphs & level curves",
        "Level surfaces",
        "Limits in R²",
        "Continuity in R²",
        "Domain in several variables",
        "Quadric surfaces review",
    ]),
    ("Partial derivatives", [
        "Partial derivatives",
        "Higher partials & Clairaut",
        "Tangent planes",
        "Linear approximation (multi)",
        "Chain rule (multi)",
        "Directional derivatives",
        "Gradient vector",
        "Gradient & level sets",
        "Implicit differentiation (multi)",
        "Differentiability in Rⁿ",
        "Jacobian matrix",
        "Taylor in two variables",
    ]),
    ("Optimization", [
        "Critical points in R²",
        "Second derivative test (multi)",
        "Absolute extrema on regions",
        "Lagrange multipliers",
        "Constrained optimization apps",
        "Least squares as opt",
        "Gradient descent glimpse",
        "Convexity intro",
    ]),
    ("Multiple integrals", [
        "Double integrals over rectangles",
        "Iterated integrals",
        "Fubini's theorem",
        "Double integrals over regions",
        "Polar double integrals",
        "Applications: mass, center",
        "Triple integrals",
        "Cylindrical coordinates",
        "Spherical coordinates",
    ]),
    ("Vector calculus", [
        "Vector fields",
        "Line integrals (scalar)",
        "Line integrals (vector)",
        "Conservative fields",
        "Fundamental theorem for lines",
        "Green's theorem",
        "Curl & divergence",
        "Parametric surfaces",
        "Surface integrals (scalar)",
        "Flux integrals",
        "Stokes' theorem",
        "Divergence theorem",
        "Path independence",
        "Potential functions",
        "Applications: work & flow",
        "Maxwell glimpse",
        "Differential forms taste",
        "When theorems apply",
    ]),
    ("First-order equations", [
        "Review separable & linear",
        "Exact equations",
        "Integrating factors (exact)",
        "Homogeneous first-order",
        "Bernoulli equations",
        "Substitutions",
        "Qualitative analysis",
    ]),
    ("Second-order linear", [
        "Linear 2nd-order structure",
        "Homogeneous constant coeff",
        "Characteristic equation",
        "Repeated & complex roots",
        "Nonhomogeneous: undetermined",
        "Variation of parameters",
        "Spring–mass systems",
        "Damping regimes",
        "Forced oscillations",
        "Resonance",
        "Cauchy–Euler equations",
        "Boundary value intro",
        "Reduction of order",
    ]),
    ("Systems of ODEs", [
        "First-order systems",
        "Convert higher-order to system",
        "Matrix form x′=Ax",
        "Eigen-method for systems",
        "Phase portraits (2D)",
        "Spiral, node, saddle",
        "Nonhomogeneous systems",
        "Linearization of nonlinear",
        "Predator–prey glimpse",
        "Coupled springs",
        "Stability language",
    ]),
    ("Laplace transform", [
        "Definition & existence",
        "Transforms of basics",
        "s-shift & t-shift",
        "Solve IVP with Laplace",
        "Step & impulse functions",
        "Convolution",
        "Transfer functions glimpse",
        "Partial fractions (Laplace)",
        "Systems via Laplace",
    ]),
    ("Fourier series", [
        "Periodic functions",
        "Fourier coefficients",
        "Sine & cosine series",
        "Convergence idea",
        "Even/odd extensions",
        "Half-range expansions",
        "Parseval glimpse",
        "PDE motivation (heat/wave)",
    ]),
]

def era_block(era_id, name, roman, metaphor, tagline, unlock, domains_spec, roman_str):
    domains = []
    total = 0
    for di, (dname, titles) in enumerate(domains_spec, 1):
        skills = make_skills(roman_str, di, titles, starter_n=2 if unlock else 0)
        # For locked-ish early eras with unlock True, first domain gets growing
        domains.append({
            "id": f"{roman_str}.{di}",
            "name": dname,
            "skills": skills,
        })
        total += len(skills)
    return {
        "id": era_id,
        "name": name,
        "roman": roman,
        "romanLabel": roman_str,
        "unlock": unlock,
        "metaphor": metaphor,
        "tagline": tagline,
        "total": total,
        "domains": domains,
    }

def placeholders(era_id, name, roman, metaphor, tagline, unlock, branch_names, per=12):
    # 7 lightweight domains
    specs = []
    for i, bn in enumerate(branch_names):
        titles = [f"{bn} · {j:02d}" for j in range(1, per + 1)]
        # richer for Count first branch
        specs.append((bn, titles))
    return era_block(era_id, name, roman, metaphor, tagline, unlock, specs, ["I","II","III","IV","V","VI","VII"][roman])

# Count: keep earlier tree sample feel
COUNT_DOMAINS = [
    ("Counting", [
        "Count objects one by one", "Count to 10", "Count to 20", "Count to 50",
        "Count to 100", "Count back from 10", "Count back from 20", "Find one more",
        "Find one less", "Ordinal positions", "Skip count by 2s", "Skip count by 5s",
        "Skip count by 10s", "Count on from any number", "Count collections", "Estimate then check",
    ]),
    ("Number Sense", pad([], 14, "Number sense")),
    ("Place Value", pad([], 14, "Place value")),
    ("Comparing", pad([], 12, "Comparing")),
    ("Patterns", pad([], 12, "Patterns")),
    ("Early Ops", pad([], 14, "Early ops")),
    ("Measure & Data", [
        "Compare lengths", "Order by length", "Nonstandard units", "Measure with a ruler",
        "Compare weights", "Compare capacity", "Time to the hour", "Time to the half hour",
        "Days and months", "Read a calendar", "Coins", "Make amounts",
        "Tally marks", "Picture graphs", "Bar graphs", "Ask with data",
    ]),
]

def main():
    # Fix Number Sense etc with plausible titles
    COUNT_DOMAINS[1] = ("Number Sense", [
        "Subitize small sets", "Same amount different look", "More & less", "Equal groups",
        "Part–part–whole", "Number bonds to 10", "Number bonds to 20", "Make 10",
        "Doubles", "Near doubles", "Zero the hero", "Compose teen numbers",
        "Decompose teen numbers", "Mental images of quantity",
    ])
    COUNT_DOMAINS[2] = ("Place Value", [
        "Tens and ones", "Bundle tens", "Hundreds chart", "Read 2-digit numbers",
        "Write 2-digit numbers", "Expanded form (2-digit)", "10 more / 10 less",
        "100 more / 100 less", "Compare 2-digit", "Round to tens", "3-digit place value",
        "Expanded form (3-digit)", "Number line placement", "Rename units",
    ])
    COUNT_DOMAINS[3] = ("Comparing", [
        "Match to compare", "More, fewer, same", "Compare with symbols", "Order three numbers",
        "Compare on number line", "Closest to", "Between", "Inequality language",
        "Compare lengths as numbers", "Compare sets without counting", "True/false number sentences",
        "Estimation comparisons",
    ])
    COUNT_DOMAINS[4] = ("Patterns", [
        "Copy a pattern", "Extend AB patterns", "Extend ABC patterns", "Name the rule",
        "Growing patterns", "Number patterns", "Patterns on hundred chart", "Odd & even patterns",
        "Input–output tables", "Pattern bugs", "Create a pattern", "Patterns in shapes",
    ])
    COUNT_DOMAINS[5] = ("Early Ops", [
        "Add with objects", "Subtract with objects", "Add within 10", "Subtract within 10",
        "Add within 20", "Subtract within 20", "Put together stories", "Take apart stories",
        "Compare stories", "Unknown addend", "Make a ten to add", "Count on to add",
        "Doubles to add", "Relate add & subtract",
    ])

    eras = [
        era_block("count", "Count", 0, "tree", "Things begin here.", True, COUNT_DOMAINS, "I"),
        placeholders("operate", "Operate", 1, "city", "Do things to numbers.", True,
                     ["Add", "Subtract", "Multiply", "Divide", "Properties", "Fluency", "Word Work"], 14),
        placeholders("relate", "Relate", 2, "bridges", "See connections.", False,
                     ["Ratio", "Proportion", "Linear", "Systems", "Inequalities", "Graphs", "Models"], 12),
        era_block("solve", "Solve", 3, "mountains", "Find the unknown.", True, IV, "IV"),
        era_block("prove", "Prove", 4, "palace", "Know it's true.", True, V, "V"),
        era_block("motion", "Motion", 5, "ocean", "Understand change.", True, VI, "VI"),
        era_block("space", "Space", 6, "cosmos", "Explore higher worlds.", True, VII, "VII"),
    ]

    # Verify IV–VII counts
    expected = {"solve": 199, "prove": 173, "motion": 174, "space": 197}
    report = {}
    for e in eras:
        report[e["id"]] = {
            "total": e["total"],
            "domains": [(d["id"], d["name"], len(d["skills"])) for d in e["domains"]],
        }
        if e["id"] in expected:
            assert e["total"] == expected[e["id"]], (e["id"], e["total"], expected[e["id"]])
            for d, (name, titles) in zip(e["domains"], {"solve": IV, "prove": V, "motion": VI, "space": VII}[e["id"]]):
                assert len(d["skills"]) == len(titles), (d["id"], len(d["skills"]), len(titles))

    iv_vii = sum(e["total"] for e in eras if e["id"] in expected)
    assert iv_vii == 743, iv_vii

    doc = {
        "version": 1,
        "generated": "prototype-invented-titles",
        "note": "Skill titles invented to match domain outline counts; original 743-skill paste unavailable.",
        "eras": eras,
        "stepLabels": STEPS,
    }
    out = Path("/workspace/mathera/curriculum.json")
    out.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n")
    print("Wrote", out)
    print("IV–VII total:", iv_vii)
    for e in eras:
        print(f"  {e['romanLabel']} {e['name']}: {e['total']} skills, {len(e['domains'])} domains, unlock={e['unlock']}")
        if e["id"] in expected:
            for d in e["domains"]:
                print(f"    {d['id']} {d['name']}: {len(d['skills'])}")

if __name__ == "__main__":
    main()
